
  - name: Expect Node Manager to be running
    when: nm_listening.state is defined and nm_listening.state == "stopped"
    register: nm_start
    shell: nohup ~/bin/startNodeManager.sh </dev/null >/dev/null 2>&1 &
    environment:
        USER_MEM_ARGS: "{{ user_mem_args_value }}"

  - name: Expect Node Manager to be listening
    when: nm_start.changed
    ignore_errors: yes
    register: nm_start_result
    wait_for:
        host: "{{ weblogic_node_manager_address }}"
        port: "{{ weblogic_node_manager_port }}"
        state: started
        timeout: "{{ timeout.node_manager }}"
