FRIENDLY_FULL_NAME = "Banana Cluster Control"
VERSION = "0"
CONFIG_DIR = "config"
CONFIG_EXT = "ini"
KILL_BIN = "/bin/kill"
CLIENT_NAME = "bcc"
SERVER_NAME = "bccagentd"
LOGGING_NAME = "console"
