---

- name: Write hostname and IP address to hosts file admin
  lineinfile: 
     dest: /etc/hosts
     regexp: "{{hostvars[groups['all'][0]].ansible_host}}"
     line: "{{hostvars[groups['all'][0]].ansible_host}} {{hostvars[groups['all'][0]].inventory_hostname}}"
    
- name: Write hostname and IP address to hosts file as01
  lineinfile: 
     dest: /etc/hosts 
     regexp: "{{hostvars[groups['all'][1]].ansible_host}}"
     line: "{{hostvars[groups['all'][1]].ansible_host}} {{hostvars[groups['all'][1]].inventory_hostname}}"      
    
- name: Write hostname and IP address to hosts file as02
  lineinfile: 
     dest: /etc/hosts 
     regexp: "{{hostvars[groups['all'][2]].ansible_host}}"
     line: "{{hostvars[groups['all'][2]].ansible_host}} {{hostvars[groups['all'][2]].inventory_hostname}}"
  when: groups["{{ weblogic_domain_name }}_as02"] is defined and (groups["{{ weblogic_domain_name }}_as02"]|length>1)
