  # - name: Expect Node Manager to be listening
    # wait_for:
        # host: "{{ weblogic_node_manager_address }}"
        # port: "{{ weblogic_node_manager_port }}"
        # state: started
        # timeout: 2

  - name: Expect Admin to be listening
    wait_for:
        host: "{{ weblogic_instance_admin_address }}"
        port: "{{ weblogic_instance_admin_port }}"
        state: started
        timeout: 2

  - name: Expect the presence of the {{ script_start_managed }} script
    template: 
        src: "{{ script_start_managed }}"
        dest: "{{ domain_account.home }}/{{ script_start_managed }}"

  - name: Discover {{ weblogic_instance_name }}'s listening state
    register: managed_listening
    failed_when: no
    wait_for:
        host: "{{ weblogic_instance_address }}"
        port: "{{ weblogic_instance_port }}"
        state: stopped
        timeout: 2

  - name: Expect {{ weblogic_instance_name }} to be running
    when: managed_listening.state is defined and managed_listening.state == "stopped"
    register: managed_start
    shell: "{{ weblogic_install.oracle_home }}/wlserver/common/bin/wlst.sh {{ script_start_managed }}"
    args:
        executable: /bin/bash
        chdir: "{{ domain_account.home }}"

  - name: Expect {{ weblogic_instance_name }} to be listening
    when: managed_start.changed
    wait_for:
        host: "{{ weblogic_instance_address }}"
        port: "{{ weblogic_instance_port }}"
        state: started
        timeout: "{{ timeout.managed }}"
