  # - name: Expect Node Manager to be listening
    # when:  admin_listening.state is defined and admin_listening.state == "started"
    # register: nm_check
    # wait_for:
        # host: "{{ weblogic_node_manager_address }}"
        # port: "{{ weblogic_node_manager_port }}"
        # state: started
        # timeout: 2

  - name: Expect the presence of the {{ script_stop_admin }} script
    template: 
        src: "{{ script_stop_admin }}"
        dest: "{{ domain_account.home }}/{{ script_stop_admin }}"


  - name: Expect {{ weblogic_instance_name }} to be listening
    register: admin_listening
    failed_when: no
    wait_for:
        host: "{{ weblogic_instance_address }}"
        port: "{{ weblogic_instance_port }}"
        state: started
        timeout: 2

        
  - name: Expect {{ weblogic_instance_name }} to stop running
    when:  admin_listening.state is defined and admin_listening.state == "started"
    register: admin_stop
    command: "{{ weblogic_install.oracle_home }}/wlserver/common/bin/wlst.sh {{ script_stop_admin }}"
    args:
        chdir: "{{ domain_account.home }}"

  - name: Expect {{ weblogic_instance_name }} to stop listening
    when: admin_stop.changed
    wait_for:
        host: "{{ weblogic_instance_address }}"
        port: "{{ weblogic_instance_port }}"
        state: stopped
        timeout: "{{ timeout.admin }}"
